version: 0.2   
   
phases:   
    install:   
        runtime-versions:   
            java: openjdk11   
    build:   
        commands:   
            - java --version   
            - mvn test 
    post_build:
        commands:
            - echo Build completed on `date`
            - mvn package
artifacts:
    files:
        - README.md
        - target/obeo-1.0-SNAPSHOT.jar
        - appspec.yml
        - start_server.sh
        - lib/*
    discard-paths: no


    